apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-

configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap

resources:
- ../../base
- pvc.yaml

patchesStrategicMerge:
- deployment.yaml
- ingress.yaml

images:
- name: ceappacr.azurecr.io/sjh-api
  newTag: "202410220848"
- name: cepgbaseacr.azurecr.io/sjh-api
  newTag: ${{ steps.gen-version.outputs.VERSION }}
