apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-

configMapGenerator:
- files:
  - application.yaml  # 확장자를 'yaml'로 맞춤
  name: cloud-sample-configmap

resources:
- ../../base
- pvc.yaml
- deployment.yaml
- ingress.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: sjh-api
  path: deployment-patch.yaml  # 필요시 패치 파일

images:
- name: ceappacr.azurecr.io/sjh-api
  newTag: "202410220934"
- name: cepgbaseacr.azurecr.io/sjh-api
  newTag: ${{ steps.gen-version.outputs.VERSION }}
