apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-

configMapGenerator:
- name: cloud-sample-configmap
  files:
    - application.yml

resources:
- ../../base
- pvc.yaml

patchesStrategicMerge:
- deployment.yaml
- ingress.yaml

images:
- name: cepgbaseacr.azurecr.io/sjh-api
  newTag: "${{ steps.gen-version.outputs.VERSION }}"
