apiVersion: apps/v1
kind: Deployment
metadata:
  name: sjh-api  # 서비스 이름을 sjh-api로 변경
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sjh-api  # 레이블을 sjh-api로 변경
  template:
    metadata:
      labels:
        app: sjh-api  # 레이블을 sjh-api로 변경
    spec:
      containers:
        - name: sjh-api  # 컨테이너 이름을 sjh-api로 변경
          image: cepgbaseacr.azurecr.io/sjh-api:latest  # 기본 이미지 설정
          ports:
            - containerPort: 8080  # 컨테이너 포트 설정
          volumeMounts:
          - mountPath: /mnt/cloud-sample
            name: cloud-sample-volume
            readOnly: false
            subPath: cloud-sample
          - mountPath: /config
            name: application-properties
            readOnly: true
      volumes:
      - name: cloud-sample-volume
        persistentVolumeClaim:
          claimName: cepg-aa-std-pvc  # PVC 이름을 기존과 동일하게 유지
      - name: application-properties
        configMap:
          name: cloud-sample-configmap  # ConfigMap 이름을 기존과 동일하게 유지
          items:
            - key: application.yml
              path: application.yml
          defaultMode: 420
